### ISSUE TITLE
On clean master

### ISSUE THREAD

**Issue by baugarten** [baugarten/cs162#12]
nachos.machine.AssertionFailureError
    at nachos.machine.Lib.assertTrue(Lib.java:77)
    at nachos.machine.TCB.destroy(TCB.java:175)
    at nachos.threads.KThread.restoreState(KThread.java:402)
    at nachos.threads.KThread.run(KThread.java:383)
    at nachos.threads.KThread.runNextThread(KThread.java:346)
    at nachos.threads.KThread.yield(KThread.java:246)
    at nachos.threads.Alarm.timerInterrupt(Alarm.java:45)
    at nachos.threads.Alarm$1.run(Alarm.java:25)
    at nachos.machine.Timer.timerInterrupt(Timer.java:69)
    at nachos.machine.Timer.access$0(Timer.java:62)
    at nachos.machine.Timer$1.run(Timer.java:30)
    at nachos.machine.Interrupt.checkIfDue(Interrupt.java:184)
    at nachos.machine.Interrupt.tick(Interrupt.java:152)
    at nachos.machine.Interrupt.setStatus(Interrupt.java:100)
    at nachos.machine.Interrupt.enable(Interrupt.java:64)
    at nachos.threads.Condition2.wakeAll(Condition2.java:72)
    at nachos.threads.KThread.finish(KThread.java:210)
    at nachos.threads.KThread.runThread(KThread.java:171)
    at nachos.threads.KThread.access$1(KThread.java:168)
    at nachos.threads.KThread$1.run(KThread.java:159)
    at nachos.machine.TCB.threadroot(TCB.java:235)
    at nachos.machine.TCB.access$3(TCB.java:210)
    at nachos.machine.TCB$1.run(TCB.java:93)
    at java.lang.Thread.run(Thread.java:680)

**Comment by ducky64** [comment]
I just pulled master, and I'm not getting any bugs running the main code. Or is this the unittests?

**Comment by baugarten** [comment]
When I run my test file it fails starting up the OS

**Comment by ducky64** [comment]
Running NACHOS works for me.

nachos 5.0j initializing... config interrupt timer user-check grader
**\* thread 0 looped 0 times
**\* thread 1 looped 0 times
**\* thread 0 looped 1 times
**\* thread 1 looped 1 times
**\* thread 0 looped 2 times
**\* thread 1 looped 2 times
**\* thread 0 looped 3 times
**\* thread 1 looped 3 times
**\* thread 0 looped 4 times
**\* thread 1 looped 4 times
Machine halting!

Do you have a different selfTest() in ThreadedKernel.java?

**Comment by baugarten** [comment]
I just reverted back a commit.

I must have done something stupid
